export const NAV_LINKS = [
  { href: "/programs", label: "Programs" },
  { href: "/compare", label: "Compare" },
  { href: "/blog", label: "Blog" },
  { href: "/about", label: "About" },
  { href: "/contact", label: "Contact" },
] as const;

export const STAGES = [
  { stage: 1, label: "Qualification", description: "Initial eligibility assessment" },
  { stage: 2, label: "Onboarding", description: "Welcome and advisor assignment" },
  { stage: 3, label: "Document Collection", description: "Gathering required documents" },
  { stage: 4, label: "Due Diligence", description: "Background verification" },
  { stage: 5, label: "Submission", description: "Application submitted to government" },
  { stage: 6, label: "Government Review", description: "Awaiting government decision" },
  { stage: 7, label: "Approval & Issuance", description: "Citizenship or residency granted" },
] as const;

export const REGIONS = [
  { value: "caribbean", label: "Caribbean", emoji: "🌴" },
  { value: "europe", label: "Europe", emoji: "🏰" },
  { value: "middle_east", label: "Middle East", emoji: "🕌" },
  { value: "asia_pacific", label: "Asia Pacific", emoji: "🏯" },
  { value: "south_america", label: "South America", emoji: "🌎" },
  { value: "central_america", label: "Central America", emoji: "🌮" },
  { value: "global", label: "Global", emoji: "🌐" },
] as const;

export type Region = (typeof REGIONS)[number]["value"];

export interface Program {
  name: string;
  slug: string;
  country: string;
  type: "CBI" | "Residency" | "Golden Visa" | "Trust";
  region: Region;
  minInvestment: number;
  maxInvestment: number | null;
  currency: string;
  processingTimeMonths: number | null;
  visaFreeCount: number | null;
  description: string;
  benefits: string[];
  requirements: string[];
  radarScores: {
    cost_score: number;
    speed_score: number;
    lifestyle_score: number;
    tax_score: number;
    travel_score: number;
  };
  excludedNationalities: string[];
  marketingHook: string;
  isActive: boolean;
  featured: boolean;
  exclusive: boolean;
  flagEmoji: string;
}

export const PROGRAMS: Program[] = [
  {
    name: "St Kitts & Nevis CBI",
    slug: "st-kitts-and-nevis",
    country: "St Kitts & Nevis",
    type: "CBI",
    region: "caribbean",
    minInvestment: 250000,
    maxInvestment: 400000,
    currency: "USD",
    processingTimeMonths: 4,
    visaFreeCount: 156,
    description: "The world's oldest and most reputable Citizenship by Investment program. Gain visa-free access to 150+ countries with a donation from $250,000 or real estate from $400,000.",
    benefits: ["Visa-free travel to 156 countries", "No residency requirement", "Includes dependents", "Tax-friendly jurisdiction", "Dual citizenship allowed"],
    requirements: ["Clean criminal record", "Proof of funds", "Health certificate", "Due diligence clearance"],
    radarScores: { cost_score: 50, speed_score: 70, lifestyle_score: 60, tax_score: 85, travel_score: 80 },
    excludedNationalities: ["AF", "IR", "KP", "SO", "SD", "YE", "RU", "BY"],
    marketingHook: "The world's oldest and most trusted CBI programme  - Caribbean citizenship with visa-free access to 156 countries.",
    isActive: true,
    featured: true,
    exclusive: false,
    flagEmoji: "🇰🇳",
  },
  {
    name: "Dominica CBI",
    slug: "dominica",
    country: "Dominica",
    type: "CBI",
    region: "caribbean",
    minInvestment: 100000,
    maxInvestment: 200000,
    currency: "USD",
    processingTimeMonths: 4,
    visaFreeCount: 144,
    description: "One of the most affordable CBI programs in the world. Dominica offers citizenship through a $100,000 donation to the Economic Diversification Fund.",
    benefits: ["Visa-free travel to 144 countries", "Most affordable CBI program", "No residency requirement", "Tax-free on foreign income", "Family inclusion"],
    requirements: ["Clean criminal record", "Proof of funds", "Health certificate", "Due diligence clearance"],
    radarScores: { cost_score: 70, speed_score: 70, lifestyle_score: 45, tax_score: 85, travel_score: 74 },
    excludedNationalities: ["AF", "IR", "KP", "SO", "SD", "YE", "RU", "BY"],
    marketingHook: "The most affordable Caribbean citizenship  - full second passport from just $100,000 with no residency required.",
    isActive: true,
    featured: true,
    exclusive: false,
    flagEmoji: "🇩🇲",
  },
  {
    name: "Grenada CBI",
    slug: "grenada",
    country: "Grenada",
    type: "CBI",
    region: "caribbean",
    minInvestment: 150000,
    maxInvestment: 350000,
    currency: "USD",
    processingTimeMonths: 5,
    visaFreeCount: 148,
    description: "Grenada's CBI provides access to the US E-2 Treaty Investor Visa, making it uniquely attractive for those seeking US market access alongside Caribbean citizenship.",
    benefits: ["US E-2 Treaty Visa eligibility", "Visa-free travel to 148 countries", "No residency requirement", "Tax advantages", "China visa-free"],
    requirements: ["Clean criminal record", "Proof of funds", "Health certificate", "Due diligence clearance"],
    radarScores: { cost_score: 60, speed_score: 60, lifestyle_score: 55, tax_score: 85, travel_score: 76 },
    excludedNationalities: ["IR", "KP", "RU", "BY"],
    marketingHook: "The only Caribbean passport with US E-2 Treaty Visa access  - Grenada citizenship opens doors to both Caribbean and American markets.",
    isActive: true,
    featured: true,
    exclusive: false,
    flagEmoji: "🇬🇩",
  },
  {
    name: "Antigua & Barbuda CBI",
    slug: "antigua-and-barbuda",
    country: "Antigua & Barbuda",
    type: "CBI",
    region: "caribbean",
    minInvestment: 230000,
    maxInvestment: 400000,
    currency: "USD",
    processingTimeMonths: 4,
    visaFreeCount: 151,
    description: "Antigua offers one of the fastest CBI programs in the Caribbean with multiple investment routes including donation, real estate, and business investment.",
    benefits: ["Visa-free travel to 151 countries", "5-day residency requirement only", "Family-friendly program", "No income tax", "Fast processing"],
    requirements: ["Clean criminal record", "Proof of funds", "Health certificate", "5 days residency in 5 years"],
    radarScores: { cost_score: 52, speed_score: 70, lifestyle_score: 62, tax_score: 85, travel_score: 78 },
    excludedNationalities: ["AF", "IR", "KP", "SO", "SD", "YE", "RU", "BY"],
    marketingHook: "Caribbean citizenship with zero income tax, family-friendly pricing, and 150+ visa-free destinations.",
    isActive: true,
    featured: false,
    exclusive: false,
    flagEmoji: "🇦🇬",
  },
  {
    name: "St Lucia CBI",
    slug: "st-lucia",
    country: "St Lucia",
    type: "CBI",
    region: "caribbean",
    minInvestment: 100000,
    maxInvestment: 300000,
    currency: "USD",
    processingTimeMonths: 4,
    visaFreeCount: 146,
    description: "St Lucia's CBI program offers competitive pricing and multiple investment options, including government bonds and real estate investment.",
    benefits: ["Visa-free travel to 146 countries", "Multiple investment options", "No residency requirement", "Tax incentives", "Family inclusion"],
    requirements: ["Clean criminal record", "Proof of funds", "Health certificate", "Due diligence clearance"],
    radarScores: { cost_score: 70, speed_score: 70, lifestyle_score: 58, tax_score: 85, travel_score: 75 },
    excludedNationalities: ["IR", "KP", "RU", "BY"],
    marketingHook: "St Lucia citizenship from $100,000  - one of the Caribbean's best-value passports with multiple investment routes.",
    isActive: true,
    featured: false,
    exclusive: false,
    flagEmoji: "🇱🇨",
  },
  {
    name: "Serbia CBI",
    slug: "serbia",
    country: "Serbia",
    type: "CBI",
    region: "europe",
    minInvestment: 250000,
    maxInvestment: 500000,
    currency: "USD",
    processingTimeMonths: 9,
    visaFreeCount: 136,
    description: "An exclusive European citizenship program available through our partner network. Serbia offers a strategic gateway to Europe with strong passport strength.",
    benefits: ["European citizenship", "Visa-free Schengen access", "EU candidate country", "Strategic location", "Growing economy"],
    requirements: ["Clean criminal record", "Proof of investment", "Health certificate", "Background check"],
    radarScores: { cost_score: 50, speed_score: 35, lifestyle_score: 60, tax_score: 50, travel_score: 70 },
    excludedNationalities: [],
    marketingHook: "European citizenship through an exclusive investment programme  - strategic gateway to the EU.",
    isActive: true,
    featured: true,
    exclusive: true,
    flagEmoji: "🇷🇸",
  },
  {
    name: "Argentina Residency",
    slug: "argentina",
    country: "Argentina",
    type: "Residency",
    region: "south_america",
    minInvestment: 0,
    maxInvestment: 50000,
    currency: "USD",
    processingTimeMonths: 2,
    visaFreeCount: 171,
    description: "Argentina offers one of the easiest residency paths in the world with a pathway to citizenship in just 2 years. No investment required.",
    benefits: ["Fast path to citizenship (2 years)", "Low cost of living", "No investment required", "Mercosur access", "Rich culture"],
    requirements: ["Valid passport", "Clean criminal record", "Proof of income", "Health certificate"],
    radarScores: { cost_score: 100, speed_score: 80, lifestyle_score: 55, tax_score: 40, travel_score: 88 },
    excludedNationalities: [],
    marketingHook: "Residency with a path to citizenship in just 2 years  - no investment required.",
    isActive: true,
    featured: false,
    exclusive: false,
    flagEmoji: "🇦🇷",
  },
  {
    name: "Chile Residency",
    slug: "chile",
    country: "Chile",
    type: "Residency",
    region: "south_america",
    minInvestment: 0,
    maxInvestment: 50000,
    currency: "USD",
    processingTimeMonths: 4,
    visaFreeCount: 174,
    description: "Chile provides a stable, modern residency option in South America with a pathway to one of the strongest passports in the region.",
    benefits: ["Strong passport (174 countries)", "Stable economy", "Path to citizenship (5 years)", "Low corruption", "Modern infrastructure"],
    requirements: ["Valid passport", "Clean criminal record", "Proof of income or employment", "Health certificate"],
    radarScores: { cost_score: 100, speed_score: 60, lifestyle_score: 65, tax_score: 45, travel_score: 89 },
    excludedNationalities: [],
    marketingHook: "Stable South American residency with one of the region's strongest passports.",
    isActive: true,
    featured: false,
    exclusive: false,
    flagEmoji: "🇨🇱",
  },
  {
    name: "Slovakia Residency",
    slug: "slovakia",
    country: "Slovakia",
    type: "Residency",
    region: "europe",
    minInvestment: 5000,
    maxInvestment: 50000,
    currency: "EUR",
    processingTimeMonths: 3,
    visaFreeCount: 183,
    description: "Slovakia offers EU residency through business establishment, providing access to the entire European Union market and Schengen area.",
    benefits: ["EU residency", "Schengen area access", "Low setup costs", "Path to EU citizenship", "Central European location"],
    requirements: ["Business establishment", "Clean criminal record", "Proof of accommodation", "Health insurance"],
    radarScores: { cost_score: 95, speed_score: 70, lifestyle_score: 70, tax_score: 40, travel_score: 94 },
    excludedNationalities: [],
    marketingHook: "EU residency from just $5,000 through business establishment  - Schengen access included.",
    isActive: true,
    featured: false,
    exclusive: false,
    flagEmoji: "🇸🇰",
  },
  {
    name: "Georgia Residency",
    slug: "georgia",
    country: "Georgia",
    type: "Residency",
    region: "europe",
    minInvestment: 0,
    maxInvestment: 100000,
    currency: "USD",
    processingTimeMonths: 1,
    visaFreeCount: 115,
    description: "Georgia offers a remarkably easy residency program with low taxes and a thriving expat community. A favorite for digital nomads and entrepreneurs.",
    benefits: ["1% personal income tax (small business)", "Easy setup", "Low cost of living", "Growing tech hub", "No visa needed for 1 year (many nationalities)"],
    requirements: ["Valid passport", "Proof of income", "Clean criminal record"],
    radarScores: { cost_score: 100, speed_score: 85, lifestyle_score: 55, tax_score: 90, travel_score: 59 },
    excludedNationalities: [],
    marketingHook: "Effortless residency with 1% tax  - Georgia is the digital nomad's gateway to Europe.",
    isActive: true,
    featured: false,
    exclusive: false,
    flagEmoji: "🇬🇪",
  },
  {
    name: "Dubai Residency",
    slug: "dubai",
    country: "UAE",
    type: "Residency",
    region: "middle_east",
    minInvestment: 100000,
    maxInvestment: 550000,
    currency: "AED",
    processingTimeMonths: 2,
    visaFreeCount: 183,
    description: "Dubai offers world-class residency options through business setup or property investment, with zero income tax and a luxury lifestyle.",
    benefits: ["0% income tax", "World-class infrastructure", "Strategic global location", "Multiple visa options", "Golden Visa available"],
    requirements: ["Business license or property investment", "Health insurance", "Clean criminal record", "Proof of funds"],
    radarScores: { cost_score: 70, speed_score: 80, lifestyle_score: 88, tax_score: 100, travel_score: 94 },
    excludedNationalities: ["KP", "IR", "SY"],
    marketingHook: "Zero income tax, world-class lifestyle  - Dubai's Golden Visa is the ultimate base for global entrepreneurs.",
    isActive: true,
    featured: true,
    exclusive: false,
    flagEmoji: "🇦🇪",
  },
  {
    name: "Portugal Golden Visa",
    slug: "portugal",
    country: "Portugal",
    type: "Golden Visa",
    region: "europe",
    minInvestment: 250000,
    maxInvestment: 500000,
    currency: "EUR",
    processingTimeMonths: 9,
    visaFreeCount: 191,
    description: "Portugal's Golden Visa is one of Europe's premier residency programs, offering a path to EU citizenship with minimal stay requirements.",
    benefits: ["EU residency & path to citizenship", "Schengen area access", "Minimal stay requirement (7 days/year)", "Family inclusion", "Strong passport (191 countries)"],
    requirements: ["Qualifying investment (fund or business)", "Clean criminal record", "Health insurance", "Proof of funds"],
    radarScores: { cost_score: 50, speed_score: 35, lifestyle_score: 85, tax_score: 50, travel_score: 98 },
    excludedNationalities: ["AF", "KP", "IR", "SY"],
    marketingHook: "Your EU gateway  - residency in Portugal with just 7 days a year and a path to one of the world's strongest passports.",
    isActive: true,
    featured: true,
    exclusive: false,
    flagEmoji: "🇵🇹",
  },
  {
    name: "Greece Golden Visa",
    slug: "greece",
    country: "Greece",
    type: "Golden Visa",
    region: "europe",
    minInvestment: 250000,
    maxInvestment: 500000,
    currency: "EUR",
    processingTimeMonths: 5,
    visaFreeCount: 188,
    description: "Greece offers one of Europe's most affordable Golden Visa programs through real estate investment, with full Schengen area access.",
    benefits: ["EU residency", "Schengen area access", "Real estate investment", "No minimum stay", "Path to citizenship (7 years)"],
    requirements: ["Real estate investment", "Clean criminal record", "Health insurance", "Proof of funds"],
    radarScores: { cost_score: 50, speed_score: 55, lifestyle_score: 78, tax_score: 40, travel_score: 96 },
    excludedNationalities: ["AF", "KP", "IR", "SY"],
    marketingHook: "EU residency through Mediterranean real estate  - Schengen access, no minimum stay.",
    isActive: true,
    featured: false,
    exclusive: false,
    flagEmoji: "🇬🇷",
  },
  {
    name: "El Salvador Residency",
    slug: "el-salvador",
    country: "El Salvador",
    type: "Residency",
    region: "central_america",
    minInvestment: 0,
    maxInvestment: 100000,
    currency: "USD",
    processingTimeMonths: 2,
    visaFreeCount: 130,
    description: "El Salvador offers fast residency with Bitcoin-friendly policies and a growing freedom-focused community. Territorial tax system.",
    benefits: ["Territorial tax system", "Bitcoin legal tender", "Low cost of living", "Fast processing", "Freedom-oriented community"],
    requirements: ["Valid passport", "Clean criminal record", "Proof of income", "Background check"],
    radarScores: { cost_score: 100, speed_score: 80, lifestyle_score: 40, tax_score: 80, travel_score: 67 },
    excludedNationalities: [],
    marketingHook: "Fast residency with territorial taxation and Bitcoin-friendly policies.",
    isActive: true,
    featured: false,
    exclusive: false,
    flagEmoji: "🇸🇻",
  },
  {
    name: "Panama Residency",
    slug: "panama",
    country: "Panama",
    type: "Residency",
    region: "central_america",
    minInvestment: 0,
    maxInvestment: 300000,
    currency: "USD",
    processingTimeMonths: 6,
    visaFreeCount: 142,
    description: "Panama offers multiple residency options including the popular Friendly Nations Visa and Pensionado programme. A strategic hub connecting North and South America with a territorial tax system.",
    benefits: ["Territorial tax system", "Friendly Nations Visa available", "USD-based economy", "Strategic global hub", "Path to citizenship (5 years)", "No worldwide income tax"],
    requirements: ["Valid passport", "Clean criminal record", "Proof of economic ties or income", "Health certificate", "Bank reference letter"],
    radarScores: { cost_score: 85, speed_score: 50, lifestyle_score: 70, tax_score: 80, travel_score: 73 },
    excludedNationalities: [],
    marketingHook: "Panama's territorial tax system and Friendly Nations Visa make it a top-tier residency for global entrepreneurs.",
    isActive: true,
    featured: false,
    exclusive: false,
    flagEmoji: "🇵🇦",
  },
  {
    name: "Asset Protection Trust",
    slug: "asset-protection-trust",
    country: "Global",
    type: "Trust",
    region: "global",
    minInvestment: 50000,
    maxInvestment: 500000,
    currency: "USD",
    processingTimeMonths: 2,
    visaFreeCount: null,
    description: "Offshore asset protection trusts provide a legal framework to shield wealth from lawsuits, creditors, and political instability.",
    benefits: ["Legal asset protection", "Privacy", "Estate planning benefits", "Multi-jurisdictional", "Creditor protection"],
    requirements: ["Legal consultation", "Proof of asset ownership", "KYC documentation"],
    radarScores: { cost_score: 80, speed_score: 80, lifestyle_score: 0, tax_score: 70, travel_score: 0 },
    excludedNationalities: [],
    marketingHook: "Shield your wealth with offshore asset protection  - legal, private, multi-jurisdictional.",
    isActive: true,
    featured: false,
    exclusive: false,
    flagEmoji: "🛡️",
  },
];

export const TESTIMONIALS = [
  {
    name: "James K.",
    role: "Tech Entrepreneur",
    quote: "Concierge made the entire citizenship process seamless. From initial consultation to receiving my passport, every step was handled with professionalism.",
    program: "St Kitts & Nevis CBI",
  },
  {
    name: "Sarah M.",
    role: "Investment Director",
    quote: "The qualification tool matched me with the perfect programme for my family. Their advisory team's expertise in European Golden Visas is unmatched.",
    program: "Portugal Golden Visa",
  },
  {
    name: "Ahmed R.",
    role: "Business Owner",
    quote: "Setting up in Dubai through Concierge was the best business decision I've made. Zero tax and world-class infrastructure  - exactly what I needed.",
    program: "Dubai Residency",
  },
];

export const FAQ_ITEMS = [
  {
    question: "What is Citizenship by Investment (CBI)?",
    answer: "CBI programmes allow individuals to obtain citizenship of a country by making a qualifying economic contribution, typically through a government donation, real estate purchase, or business investment. The process is legal, government-approved, and typically takes 3-12 months.",
  },
  {
    question: "How much does a second passport cost?",
    answer: "Costs vary significantly by programme. Caribbean CBI programmes start from $100,000 (Dominica), while European options like Portugal's Golden Visa begin at $250,000. Our qualification tool will match you with programmes within your budget.",
  },
  {
    question: "Do I need to live in the country?",
    answer: "Most CBI and Golden Visa programmes have minimal or no physical residency requirements. For example, Caribbean CBI programmes require no residency at all, while Portugal's Golden Visa requires just 7 days per year.",
  },
  {
    question: "Can my family be included?",
    answer: "Yes, nearly all programmes include your spouse and dependent children. Many Caribbean programmes also allow parents and grandparents over 55 to be included as dependents.",
  },
  {
    question: "Is dual citizenship legal?",
    answer: "Dual citizenship is permitted by most countries. All programmes we offer allow you to maintain your existing citizenship. However, some countries (like China and India) do not permit dual nationality  - we'll advise you on any implications.",
  },
  {
    question: "How long does the process take?",
    answer: "Processing times range from 1-2 months (Vanuatu, Georgia) to 6-12 months (Portugal, Malta). Caribbean CBI programmes typically process in 3-6 months. We'll give you a realistic timeline during your consultation.",
  },
];
